convert grid_io_bottom_1__0_*.png ./pdfs/grid_io_bottom_1__0_.pdf &
convert grid_io_bottom_2__0_*.png ./pdfs/grid_io_bottom_2__0_.pdf &
convert grid_io_right_3__1_*.png ./pdfs/grid_io_right_3__1_.pdf &
convert grid_io_right_3__2_*.png ./pdfs/grid_io_right_3__2_.pdf &
convert sb_2__2_*.png ./pdfs/sb_2__2_.pdf &
convert cbx_2__2_*.png ./pdfs/cbx_2__2_.pdf &
convert grid_io_top_2__3_*.png ./pdfs/grid_io_top_2__3_.pdf &
convert sb_1__2_*.png ./pdfs/sb_1__2_.pdf &
convert cbx_1__2_*.png ./pdfs/cbx_1__2_.pdf &
convert grid_io_top_1__3_*.png ./pdfs/grid_io_top_1__3_.pdf &
convert sb_0__2_*.png ./pdfs/sb_0__2_.pdf &
convert sb_0__1_*.png ./pdfs/sb_0__1_.pdf &
convert cby_0__2_*.png ./pdfs/cby_0__2_.pdf &
convert grid_io_left_0__2_*.png ./pdfs/grid_io_left_0__2_.pdf &
convert sb_0__0_*.png ./pdfs/sb_0__0_.pdf &
convert cby_0__1_*.png ./pdfs/cby_0__1_.pdf &
convert grid_io_left_0__1_*.png ./pdfs/grid_io_left_0__1_.pdf &
convert sb_1__0_*.png ./pdfs/sb_1__0_.pdf &
convert cbx_1__0_*.png ./pdfs/cbx_1__0_.pdf &
convert cby_1__1_*.png ./pdfs/cby_1__1_.pdf &
convert grid_clb_1__1_*.png ./pdfs/grid_clb_1__1_.pdf &
convert sb_2__0_*.png ./pdfs/sb_2__0_.pdf &
convert cbx_2__0_*.png ./pdfs/cbx_2__0_.pdf &
convert cby_2__1_*.png ./pdfs/cby_2__1_.pdf &
convert grid_clb_2__1_*.png ./pdfs/grid_clb_2__1_.pdf &
convert sb_2__1_*.png ./pdfs/sb_2__1_.pdf &
convert cbx_2__1_*.png ./pdfs/cbx_2__1_.pdf &
convert cby_2__2_*.png ./pdfs/cby_2__2_.pdf &
convert grid_clb_2__2_*.png ./pdfs/grid_clb_2__2_.pdf &
convert sb_1__1_*.png ./pdfs/sb_1__1_.pdf &
convert cbx_1__1_*.png ./pdfs/cbx_1__1_.pdf &
convert cby_1__2_*.png ./pdfs/cby_1__2_.pdf &
convert grid_clb_1__2_*.png ./pdfs/grid_clb_1__2_.pdf &